"""
Snapshot/regression tests for wbgt.py.

These are NOT validated against an external reference — they lock in
today's known-good output from your local environment (where thermofeel
and earthkit are installed) so that future changes (refactors, library
upgrades, dependency updates) can't silently shift behavior without you
noticing.

EXPECTED values below were generated by actually running calculate_wbgt()
with thermofeel + earthkit-meteo installed, then sanity-checked for
physical plausibility (see each test's docstring). If you change wbgt.py,
its dependencies, or their versions, rerun this file — an unexpected
change in these values is worth investigating before you trust it.
"""

import pytest

from wbgt import calculate_wbgt


# Fixed reference conditions (Bengaluru coordinates, matching wbgt.py's
# hardcoded LATITUDE/LONGITUDE) so tests are reproducible.

def test_wbgt_midday_hot_sunny():
    """
    Midday, clear sky, hot and moderately humid, decent wind.
    Note: with strong direct sun, WBGT can exceed air temp — the black
    globe term captures radiant heating that a shaded air-temp reading
    doesn't. 36.45°C against 35°C air temp is physically expected here,
    not a bug.
    """
    EXPECTED = 36.45

    result = calculate_wbgt(
        temperature_c=35.0,
        humidity=55,
        wind_kmh=10.0,
        radiation=850,
        pressure_hpa=1005,
        direct_radiation=700,
        timestamp="2026-06-15T13:00",
    )

    if EXPECTED is None:
        pytest.fail(f"Fill in EXPECTED = {result} for this scenario")
    assert result == pytest.approx(EXPECTED, abs=0.3)


def test_wbgt_night_no_radiation():
    """
    Night, zero radiation. WBGT should collapse toward the wet-bulb
    temperature (close to air temp when humidity is very high, otherwise
    noticeably below air temp).
    """
    EXPECTED = 22.44

    result = calculate_wbgt(
        temperature_c=24.0,
        humidity=85,
        wind_kmh=6.0,
        radiation=0,
        pressure_hpa=1008,
        direct_radiation=0,
        timestamp="2026-06-15T02:00",
    )

    if EXPECTED is None:
        pytest.fail(f"Fill in EXPECTED = {result} for this scenario")
    assert result == pytest.approx(EXPECTED, abs=0.3)


def test_wbgt_low_wind_high_humidity():
    """
    Near-still air, very humid, moderate sun. This is the scenario most
    likely to expose numerical issues (division by near-zero wind, etc.)
    in the convective heat transfer terms.
    """
    EXPECTED = 33.56

    result = calculate_wbgt(
        temperature_c=30.0,
        humidity=90,
        wind_kmh=1.0,
        radiation=400,
        pressure_hpa=1006,
        direct_radiation=200,
        timestamp="2026-06-15T10:00",
    )

    if EXPECTED is None:
        pytest.fail(f"Fill in EXPECTED = {result} for this scenario")
    assert result == pytest.approx(EXPECTED, abs=0.3)


def test_wbgt_hot_dry_windy():
    """
    Hot, dry, and windy. Sanity check: strong wind should pull WBGT down
    noticeably compared to the still-air case at a similar temperature.
    """
    EXPECTED = 31.32

    result = calculate_wbgt(
        temperature_c=38.0,
        humidity=25,
        wind_kmh=25.0,
        radiation=900,
        pressure_hpa=1002,
        direct_radiation=750,
        timestamp="2026-06-15T14:00",
    )

    if EXPECTED is None:
        pytest.fail(f"Fill in EXPECTED = {result} for this scenario")
    assert result == pytest.approx(EXPECTED, abs=0.3)


def test_wbgt_sunrise_boundary():
    """
    Right around sunrise, where cossza crosses from 0 to positive. Checks
    the fdir clamping logic (radiation <= 0 or direct_radiation <= 0 or
    cossza <= 0 branch in wbgt.py) doesn't blow up or return something wild.
    """
    EXPECTED = 20.13

    result = calculate_wbgt(
        temperature_c=22.0,
        humidity=80,
        wind_kmh=5.0,
        radiation=15,
        pressure_hpa=1007,
        direct_radiation=5,
        timestamp="2026-06-15T06:15",
    )

    if EXPECTED is None:
        pytest.fail(f"Fill in EXPECTED = {result} for this scenario")
    assert result == pytest.approx(EXPECTED, abs=0.3)


# --- Directional sanity checks (no exact values needed) -------------------

def test_wbgt_increases_with_humidity():
    """Holding everything else fixed, higher humidity should raise WBGT."""
    low_humidity = calculate_wbgt(
        temperature_c=32.0, humidity=30, wind_kmh=8.0, radiation=600,
        pressure_hpa=1005, direct_radiation=450, timestamp="2026-06-15T12:00",
    )
    high_humidity = calculate_wbgt(
        temperature_c=32.0, humidity=85, wind_kmh=8.0, radiation=600,
        pressure_hpa=1005, direct_radiation=450, timestamp="2026-06-15T12:00",
    )
    assert high_humidity > low_humidity


def test_wbgt_decreases_with_wind():
    """Holding everything else fixed, more wind should lower WBGT."""
    calm = calculate_wbgt(
        temperature_c=32.0, humidity=60, wind_kmh=2.0, radiation=600,
        pressure_hpa=1005, direct_radiation=450, timestamp="2026-06-15T12:00",
    )
    windy = calculate_wbgt(
        temperature_c=32.0, humidity=60, wind_kmh=20.0, radiation=600,
        pressure_hpa=1005, direct_radiation=450, timestamp="2026-06-15T12:00",
    )
    assert windy < calm


def test_wbgt_stays_within_plausible_range_of_air_temp():
    """
    WBGT should stay within a physically plausible band of air temp — not
    equal to it (that would mean humidity/wind/radiation aren't being
    applied at all), but not wildly divergent either. Note strong direct
    sun CAN push WBGT above air temp (see test_wbgt_midday_hot_sunny) —
    that's the black globe term capturing radiant heat, not a bug.
    """
    result = calculate_wbgt(
        temperature_c=35.0, humidity=60, wind_kmh=10.0, radiation=700,
        pressure_hpa=1005, direct_radiation=550, timestamp="2026-06-15T13:00",
    )
    assert result != 35.0
    assert 25.0 < result < 45.0
